### ISSUE TITLE
Error when creating project with npx

### ISSUE THREAD

**Issue by PerryDesign** [motiondeveloper/create-expression-lib#3]
Hey all, just finding out about this project. Looks great! Our tool utilizes tons of expressions and we are missing the amenities that come with working in an IDE. 

However, I am getting the following error when running `npx create-expression-lib projectName`

```
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at qo (/Users/dannyperry/.npm/_npx/3c5c635fd7b98c45/node_modules/esm/esm.js:1:223175)
    at Uo (/Users/dannyperry/.npm/_npx/3c5c635fd7b98c45/node_modules/esm/esm.js:1:222896)
    at $o (/Users/dannyperry/.npm/_npx/3c5c635fd7b98c45/node_modules/esm/esm.js:1:224488)
    at wu (/Users/dannyperry/.npm/_npx/3c5c635fd7b98c45/node_modules/esm/esm.js:1:227324)
    at Eu (/Users/dannyperry/.npm/_npx/3c5c635fd7b98c45/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/Users/dannyperry/.npm/_npx/3c5c635fd7b98c45/node_modules/esm/esm.js:1:295976)
    at n (/Users/dannyperry/.npm/_npx/3c5c635fd7b98c45/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/Users/dannyperry/.npm/_npx/3c5c635fd7b98c45/node_modules/create-expression-lib/bin/create-expression-lib:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
```

Not quite sure if this is on my end, but hoping you all might have some insight.

**Comment by PerryDesign** [comment]
Downgrading to Node version v18.17.0 fixed the issue. It was failing with the latest version of Node.

**Comment by timhaywood** [comment]
Sorry for the delay @PerryDesign! I'll take a look and see if I can get it working on the latest version of Node.
